### ISSUE TITLE
Access Example TODO App in FIGMA

### ISSUE THREAD

**Issue by lmgracia** [KlausSchaefers/figma-low-code-todo#1]
Hi @KlausSchaefers,

First of all I want to congratulate you for the work you are doing, both with Quant-UX and with this plugin for FIGMA.
In my team we are reviewing Quant-UX since some time ago.
I've been keeping an eye on this functionality, and that's why I started with this example application. I have managed to run it without any problem but I can't find detailed information on how to use the plugin in FIGMA. I think it would be very useful to have the example of the TODO app in FIGMA.
Could you share it with my user @lmgracia?

Thank you very much and congratulations for the work!

**Comment by KlausSchaefers** [comment]
Hi,

I will start creating some tutorials and documentation in the next weeks. For now,  I published the file in the community: 

https://www.figma.com/community/file/887084011990415230/Low-Code-ToDo---Blank

I hope this works for you.

**Comment by KlausSchaefers** [comment]
I added a first Video: https://youtu.be/iyu2rSbUwU8. Please feel free to share in your social accounts :D

**Comment by lmgracia** [comment]
Thank you very much for your speed.
I'll keep an eye on it right away.
